# Ollama Configuration
OLLAMA_HOST_PORT=11434
OLLAMA_HOST="localhost"
OLLAMA_CONTAINER_TAG="latest"

# Open WebUI Configuration
OPEN_WEBUI_HOST_PORT=3000
OPEN_WEBUI_HOST="localhost"
OPEN_WEBUI_CONTAINER_TAG="latest"
